### ISSUE TITLE
Keychain 2.7.1 on Ubuntu

### ISSUE THREAD

**Issue by adam-stokes** [wa/pkg-keychain#3]
It looks like Ubuntu hasn't updated their keychain package to 2.8 where --confhost is available as an option.  Would you object to a patch that checks the package version installed and append arguments based on what is available?

**Comment by faho** [comment]
How does keychain react when given that option? Error out?

If so, the patch is trivial:

``` fish
if not keychain --eval --quiet --confhost --timeout 60 | source
   keychain --eval --quiet --timeout 60 | source
end
```

**Comment by adam-stokes** [comment]
Yea it basically just exits with non-zero

```
Installing keychain...
✔ keychain succesfully installed.
keychain: unknown option --confhost
```

**Comment by adam-stokes** [comment]
What is the output from `keychain --eval` on your system? When I attempt to patch the keychain plugin locally I'm not sure how it even works because the eval output is something like:

```
SSH_AUTH_SOCK=/tmp/ssh-M6UCUpFjesVO/agent.7615; export SSH_AUTH_SOCK;
SSH_AGENT_PID=7617; export SSH_AGENT_PID;
GPG_AGENT_INFO=/tmp/gpg-qZKaen/S.gpg-agent:5222:1; export GPG_AGENT_INFO;
```

And running it results in:

```
[~/.l/s/o/p/keychain]                                                                                                
‹master*› »»»» keychain --eval --quiet|source                                                              0|20:05:22
Unsupported use of '='. In fish, please use 'set SSH_AUTH_SOCK /tmp/ssh-M6UCUpFjesVO/agent.7615'.
- (line 1): SSH_AUTH_SOCK=/tmp/ssh-M6UCUpFjesVO/agent.7615; export SSH_AUTH_SOCK;
            ^
from sourcing file -
    called on standard input

Unsupported use of '='. In fish, please use 'set SSH_AGENT_PID 7617'.
- (line 2): SSH_AGENT_PID=7617; export SSH_AGENT_PID;
            ^
from sourcing file -
    called on standard input

Unsupported use of '='. In fish, please use 'set GPG_AGENT_INFO /tmp/gpg-qZKaen/S.gpg-agent:5222:1'.
- (line 4): GPG_AGENT_INFO=/tmp/gpg-qZKaen/S.gpg-agent:5222:1; export GPG_AGENT_INFO;
            ^
from sourcing file -
    called on standard input
```

**Comment by faho** [comment]
On my system, keychain 2.8.1 outputs fish syntax:

``` fish
set -e SSH_AUTH_SOCK; set -x -U SSH_AUTH_SOCK [...];
set -e SSH_AGENT_PID; set -x -U SSH_AGENT_PID [...];
```

The history is a bit convoluted, but it seems the [initial commit for fish support](https://github.com/funtoo/keychain/commit/fcbf021434a16bb352bb2e37bf27e45d1382eaf9) was written in 2006 but only seems to have been added in 2.7.**2**, so it seems all of this is moot anyway. If that's not true, please comment.
